// Generated by CoffeeScript 1.6.3
/*
This pulls two words from the dictionary api, smashes them together
*/

var Foxglove,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Foxglove = (function() {
  function Foxglove() {
    this.success = __bind(this.success, this);
  }

  Foxglove.prototype.generateAPIUrl = function() {
    var apiKey, limit, maxLength, minLength, url;
    apiKey = '8f99033d4a9c15332f00c0e62ae083bbf4c9c998a9c928de2';
    limit = 2;
    minLength = 2;
    maxLength = 6;
    return url = "http://api.wordnik.com/v4/words.json/randomWords?hasDictionaryDef=false&includePartOfSpeech=noun&minCorpusCount=0&maxCorpusCount=-1&minDictionaryCount=1&maxDictionaryCount=-1&minLength=" + minLength + "&maxLength=" + maxLength + "&limit=" + limit + "&api_key=" + apiKey;
  };

  Foxglove.prototype.generateAndAppend = function() {
    return this.generate();
  };

  /*
  Use the dictionary API to get two nouns and smash them together
  */


  Foxglove.prototype.generate = function() {
    return $.ajax({
      url: this.generateAPIUrl(),
      type: 'GET'
    }).done(this.success);
  };

  Foxglove.prototype.success = function(r) {
    var nouns;
    nouns = this.pullDataFromResponse(r);
    this.nouns = this.smash(nouns);
    return this.appendToDocument(this.nouns);
  };

  Foxglove.prototype.appendToDocument = function(nouns) {
    var span;
    span = $('#results');
    return span.html(nouns);
  };

  Foxglove.prototype.pullDataFromResponse = function(r) {
    return [r[0].word, r[1].word];
  };

  /*
  Our current format is just to take two words and put them together
  with no spaces
  */


  Foxglove.prototype.smash = function(nouns) {
    return nouns.join('');
  };

  return Foxglove;

})();
