// Generated by CoffeeScript 1.6.3
/*
A {WordTypeWheel} contains a number of `@wordTypes` that can be re-ordered at will.
The {WordTypeWheel} will emit an event when the wheel is clicked, declaring the currently
selected wordType.  It will also allow the user to scroll between currently active wordTypes
with the flick of a finger, move of the mouse, etc.
*/

var WordTypeWheel;

WordTypeWheel = (function() {
  function WordTypeWheel() {
    this.wordTypes = ['noun', 'verb', 'adjective', 'pronoun', 'predicate'];
  }

  WordTypeWheel.prototype.getCurrent = function() {
    return this.currentWordType = this.wordTypes[2];
  };

  WordTypeWheel.prototype.up = function() {
    var type;
    type = this.wordTypes.shift();
    return this;
  };

  return WordTypeWheel;

})();
